<div class="discounts-page app-page-shell">
    <header class="app-page-hero discounts-hero">
        <div class="app-page-heading">
            <span class="app-page-icon" aria-hidden="true"><i class="bx bx-purchase-tag-alt"></i></span>
            <div><div class="app-eyebrow">Ventas · Reglas automáticas</div><h1 class="app-page-title">Descuentos</h1><p class="app-page-subtitle">Configura beneficios por temporada, producto y tipo de persona. El POS aplica automáticamente el mayor ahorro válido.</p></div>
        </div>
        @can('crear descuentos')<button type="button" class="discount-primary" wire:click="openCreate"><i class="bx bx-plus"></i><span>Nuevo descuento</span></button>@endcan
    </header>

    <section class="discount-summary" aria-label="Resumen de descuentos">
        <article><span class="is-purple"><i class="bx bx-purchase-tag"></i></span><div><small>Configurados</small><strong>{{ $this->discounts->count() }}</strong></div></article>
        <article><span class="is-green"><i class="bx bx-broadcast"></i></span><div><small>Activos</small><strong>{{ $this->discounts->where('is_active', true)->count() }}</strong></div></article>
        <article><span class="is-blue"><i class="bx bx-user-check"></i></span><div><small>Con audiencia</small><strong>{{ $this->discounts->where('audience', '!=', 'everyone')->count() }}</strong></div></article>
    </section>

    <section class="discount-directory">
        <header><div><span class="app-eyebrow">Catálogo de reglas</span><h2>Descuentos configurados</h2><p>No se acumulan entre sí: el POS selecciona el de mayor beneficio y conserva una evidencia en la orden.</p></div><div class="discount-filters"><label><i class="bx bx-search"></i><input type="search" wire:model.live.debounce.400ms="search" placeholder="Buscar descuento…"></label><select wire:model.live="statusFilter" aria-label="Filtrar por estado"><option value="all">Todos</option><option value="active">Activos</option><option value="paused">Pausados</option></select></div></header>
        <div class="discount-grid">
            @forelse($this->discounts as $discount)
                <article class="discount-card" wire:key="discount-{{ $discount->id }}">
                    <header><span class="discount-card__icon"><i class="bx {{ $discount->category === 'seasonal' ? 'bx-calendar-star' : ($discount->category === 'employee' || $discount->category === 'associate' ? 'bx-id-card' : 'bx-purchase-tag-alt') }}"></i></span><div><span class="discount-card__category">{{ $discount->categoryLabel() }}</span><h3>{{ $discount->name }}</h3></div><span class="discount-status {{ $discount->is_active ? 'is-active' : 'is-paused' }}"><i class="bx {{ $discount->is_active ? 'bx-check-circle' : 'bx-pause-circle' }}"></i>{{ $discount->is_active ? 'Activo' : 'Pausado' }}</span></header>
                    <p>{{ $discount->description ?: 'Sin descripción adicional.' }}</p>
                    <strong class="discount-benefit">{{ $discount->benefitLabel() }}</strong>
                    <dl><div><dt>Aplica a</dt><dd>{{ $discount->scope === 'products' ? $discount->products_count.' producto(s)' : 'Toda la orden' }}</dd></div><div><dt>Audiencia</dt><dd>{{ $discount->audienceLabel() }}</dd></div><div><dt>Compra mínima</dt><dd>${{ number_format((float) $discount->minimum_purchase, 2) }}</dd></div><div><dt>Vigencia</dt><dd>{{ $discount->starts_at?->format('d/m/Y H:i') ?? 'Inmediata' }} — {{ $discount->ends_at?->format('d/m/Y H:i') ?? 'Sin término' }}</dd></div></dl>
                    <div class="discount-card__tags"><span><i class="bx bx-bot"></i>Automático</span>@if($discount->combine_with_promotions)<span><i class="bx bx-layer-plus"></i>Combina promoción</span>@endif<span><i class="bx bx-sort"></i>Prioridad {{ $discount->priority }}</span></div>
                    <footer>@can('editar descuentos')<button type="button" wire:click="toggleActive({{ $discount->id }})"><i class="bx {{ $discount->is_active ? 'bx-pause' : 'bx-play' }}"></i>{{ $discount->is_active ? 'Pausar' : 'Activar' }}</button><button type="button" wire:click="openEdit({{ $discount->id }})"><i class="bx bx-edit-alt"></i>Editar</button>@endcan @can('eliminar descuentos')<button type="button" class="is-danger" wire:click="delete({{ $discount->id }})" wire:confirm="¿Eliminar este descuento?"><i class="bx bx-trash"></i>Eliminar</button>@endcan</footer>
                </article>
            @empty
                <div class="discount-empty"><span><i class="bx bx-purchase-tag"></i></span><h3>No hay descuentos configurados</h3><p>Crea una regla para Buen Fin, asociados, clientes o personal.</p>@can('crear descuentos')<button type="button" class="discount-primary" wire:click="openCreate">Crear primer descuento</button>@endcan</div>
            @endforelse
        </div>
    </section>

    @if($showEditor)
        <div class="app-modal-backdrop discount-modal-backdrop" aria-hidden="true"></div>
        <div class="app-modal-layer discount-modal-layer" role="dialog" aria-modal="true" aria-labelledby="discount-editor-title" aria-describedby="discount-editor-description" tabindex="-1" wire:key="discount-editor-modal" wire:click.self="closeEditor" wire:keydown.escape.window="closeEditor">
            <form class="discount-modal" wire:submit="save">
                <header><div><span class="app-eyebrow">{{ $editingId ? 'Actualizar regla' : 'Nueva regla' }}</span><h2 id="discount-editor-title">{{ $editingId ? 'Editar descuento' : 'Crear descuento' }}</h2><p id="discount-editor-description">Define beneficio, alcance, audiencia y vigencia.</p></div><button type="button" wire:click="closeEditor" aria-label="Cerrar editor de descuento"><i class="bx bx-x" aria-hidden="true"></i></button></header>
                <div class="discount-modal__body">
                    @if($errors->any())<div class="discount-errors" role="alert"><i class="bx bx-error-circle"></i><span><strong>Revisa la configuración.</strong><small>{{ $errors->first() }}</small></span></div>@endif
                    <fieldset><legend>1. Identidad y beneficio</legend><div class="discount-form-grid"><label class="is-wide"><span>Nombre *</span><input type="text" wire:model="name" maxlength="120" placeholder="Ej. Buen Fin 20%"></label><label><span>Tipo</span><select wire:model="category"><option value="occasional">Ocasional</option><option value="seasonal">Temporada / Buen Fin</option><option value="associate">Asociado</option><option value="customer">Cliente</option><option value="employee">Empleado</option><option value="other">Otro</option></select></label><label><span>Beneficio</span><select wire:model.live="valueType"><option value="percentage">Porcentaje</option><option value="fixed">Monto fijo</option></select></label><label><span>{{ $valueType === 'percentage' ? 'Porcentaje' : 'Monto' }} *</span><input type="number" wire:model="value" min="0.01" max="{{ $valueType === 'percentage' ? 100 : 999999 }}" step="0.01"></label><label class="is-wide"><span>Descripción</span><textarea wire:model="description" maxlength="500" rows="2" placeholder="Explica cuándo y para quién aplica."></textarea></label></div></fieldset>
                    <fieldset><legend>2. Alcance</legend><div class="discount-choice-grid"><label><input type="radio" wire:model.live="scope" value="order"><span><i class="bx bx-receipt"></i><strong>Toda la orden</strong><small>Calcula el descuento sobre todos los artículos elegibles.</small></span></label><label><input type="radio" wire:model.live="scope" value="products"><span><i class="bx bx-dish"></i><strong>Productos seleccionados</strong><small>Solo reduce los artículos que elijas.</small></span></label></div>@if($scope === 'products')<div class="discount-selector"><strong>Productos elegibles *</strong><div>@foreach($this->products as $product)<label><input type="checkbox" wire:model="productIds" value="{{ $product->id }}"><span><b>{{ $product->name }}</b><small>{{ $product->category?->name ?: 'Sin categoría' }} · ${{ number_format((float) $product->price, 2) }}</small></span></label>@endforeach</div></div>@endif<div class="discount-form-grid"><label><span>Compra mínima</span><input type="number" wire:model="minimumPurchase" min="0" step="0.01"></label><label><span>Tope de descuento</span><input type="number" wire:model="maximumDiscount" min="0.01" step="0.01" placeholder="Sin límite"></label><label class="discount-switch is-wide"><input type="checkbox" wire:model="combineWithPromotions"><span><strong>Permitir sobre productos con promoción</strong><small>Si se desactiva, las líneas con 2×1 u otra promoción quedan fuera del cálculo.</small></span></label></div></fieldset>
                    <fieldset><legend>3. Audiencia</legend><div class="discount-form-grid"><label class="is-wide"><span>¿Quién lo recibe?</span><select wire:model.live="audience"><option value="everyone">Todo público</option><option value="customers">Cualquier cliente registrado</option><option value="selected_customers">Clientes seleccionados</option><option value="employees">Todo el personal</option><option value="selected_employees">Personal seleccionado</option></select><small>Los descuentos para personal requieren identificar al beneficiario en el cobro.</small></label></div>@if($audience === 'selected_customers')<div class="discount-selector"><strong>Clientes *</strong><div>@foreach($this->customers as $customer)<label><input type="checkbox" wire:model="customerIds" value="{{ $customer->id }}"><span><b>{{ $customer->name }}</b><small>{{ $customer->phone ?: $customer->email }}</small></span></label>@endforeach</div></div>@elseif($audience === 'selected_employees')<div class="discount-selector"><strong>Personal *</strong><div>@foreach($this->employees as $employee)<label><input type="checkbox" wire:model="employeeIds" value="{{ $employee->id }}"><span><b>{{ $employee->name }}</b><small>{{ $employee->email }}</small></span></label>@endforeach</div></div>@endif</fieldset>
                    <fieldset><legend>4. Vigencia y operación</legend><div class="discount-form-grid"><label><span>Inicio</span><input type="datetime-local" wire:model="startsAt"></label><label><span>Final</span><input type="datetime-local" wire:model="endsAt"></label><label><span>Prioridad</span><input type="number" wire:model="priority" min="1" max="999"><small>Solo desempata descuentos con el mismo ahorro.</small></label><label class="discount-switch"><input type="checkbox" wire:model="isActive"><span><strong>Descuento activo</strong><small>Disponible al guardar.</small></span></label></div><div class="discount-mode-grid">@foreach(['dine_in'=>['bx-dish','Mesa'],'takeaway'=>['bx-store','Ventanilla'],'pickup'=>['bx-package','Recoger'],'delivery'=>['bx-cycling','Delivery']] as $mode=>$meta)<label><input type="checkbox" wire:model="fulfillmentModes" value="{{ $mode }}"><span><i class="bx {{ $meta[0] }}"></i>{{ $meta[1] }}</span></label>@endforeach</div></fieldset>
                </div>
                <footer><button type="button" class="discount-secondary" wire:click="closeEditor">Cancelar</button><button type="submit" class="discount-primary" wire:loading.attr="disabled" wire:target="save"><span wire:loading.remove wire:target="save">Guardar descuento</span><span wire:loading wire:target="save">Guardando…</span></button></footer>
            </form>
        </div>
    @endif
</div>
